### ISSUE TITLE
How to visualize the ground truth?

### ISSUE THREAD

**Issue by WangzcBruce** [EdwardLeeLPZ/PowerBEV#3]
I am sorry to bother you. I ran the visual.py, then only got the predictions. How can i get the gt?
![sample_171](https://github.com/EdwardLeeLPZ/PowerBEV/assets/45158420/37f93c8a-1174-4343-87a1-62743cdd56fd)

**Comment by EdwardLeeLPZ** [comment]
> I am sorry to bother you. I ran the visual.py, then only got the predictions. How can i get the gt? ![sample_171](https://user-images.githubusercontent.com/45158420/276066689-37f93c8a-1174-4343-87a1-62743cdd56fd.png)

Hi,

Since I only visualized GT when I generated the demo, I didn't include it in my code. But all it takes to accomplish this function is a simple modification to` visual.py`:

Instead of loading the input images for inference, directly load the GT from the dataloader. [(Line 113-122)](https://github.com/EdwardLeeLPZ/PowerBEV/blob/master/visualise.py#L113-L122)

For a simple implementation, you can assign `labels['segmentation']` directly to `output['segmentation']` and assign `labels['flow']` directly to `output['instance_flow']`.

Sorry I didn't keep my original implementation. If you still have difficulity in it, feel free to raise your question further.

**Comment by WangzcBruce** [comment]
![image](https://github.com/EdwardLeeLPZ/PowerBEV/assets/45158420/d527c7c3-6cab-4de0-8a2f-19d3075b5a48)
![image](https://github.com/EdwardLeeLPZ/PowerBEV/assets/45158420/7c025df6-a5d2-4789-99fc-40a7e15302c2)
There was a little trouble to replace the predictions with inputs simply. The dims between them are different.

**Comment by WangzcBruce** [comment]
![image](https://github.com/EdwardLeeLPZ/PowerBEV/assets/45158420/11c50d3a-1ba3-4ba3-861f-46366b49765f)
This function affected the operation of replacing the preditions with gts.

**Comment by EdwardLeeLPZ** [comment]
> ![image](https://user-images.githubusercontent.com/45158420/276801274-d527c7c3-6cab-4de0-8a2f-19d3075b5a48.png) ![image](https://user-images.githubusercontent.com/45158420/276801447-7c025df6-a5d2-4789-99fc-40a7e15302c2.png) There was a little trouble to replace the predictions with inputs simply. The dims between them are different.

Hi,

You are right. While the previously mentioned idea is correct, modifying the visualization really isn't that simple.
For your convenience, I've updated a version [V1.1](https://github.com/EdwardLeeLPZ/PowerBEV/commit/49c8ad7b7c067e8fee15da1e020702c3d0cc7180) and added the GT visualization to the original code.
You just need to follow the tutorial and add `VISUALIZATION.VIS_GT True` after the original command.
![image](https://github.com/EdwardLeeLPZ/PowerBEV/assets/49630295/7c8ae76b-c1ef-47e8-80a9-5065d6b10fe0)
The above modifications work fine on my computer. Please contact me further if you encounter any more problems.
