### ISSUE TITLE
how to train on own dataset?

### ISSUE THREAD

**Issue by rockywind** [EdwardLeeLPZ/PowerBEV#5]
Hi, thank you for sharing the great work! I want to train the model on own dataset. Can you give me some advice? My dataset is the same as kitti style.

**Comment by EdwardLeeLPZ** [comment]
Hi,

Since KITTI is less used in the instance prediction task, my work as well as my baseline model does not include it into the pipeline.
If you want to adapt it to the KITTI dataset, you mainly need to modify the [dataset](https://github.com/EdwardLeeLPZ/PowerBEV/blob/master/powerbev/data.py) part, especially the generation of segmentation and flow GT labels from the bounding boxes.

The main steps are as follows:

1. [Load the inputs for future frames](https://github.com/EdwardLeeLPZ/PowerBEV/blob/master/powerbev/data.py#L168-L259), including the surrounding camera images, their corresponding intrinsic and extrinsic matrices;
2. [Load the annotations for each instance](https://github.com/EdwardLeeLPZ/PowerBEV/blob/master/powerbev/data.py#L271-L326), including the category, size and position of the bounding box;
3. [Load ego vehicle positions for future frames](https://github.com/EdwardLeeLPZ/PowerBEV/blob/master/powerbev/data.py#L463-L494);
4. [Generate segmentation labels from the filtered instance annotations](https://github.com/EdwardLeeLPZ/PowerBEV/blob/master/powerbev/data.py#L425-L461), including semantic segmentations and instance segmentations;
5. [Generate flow labels based on the above segmentation labels](https://github.com/EdwardLeeLPZ/PowerBEV/blob/master/powerbev/data.py#L393-L402);
6. [Generate center and offset labels](https://github.com/EdwardLeeLPZ/PowerBEV/blob/master/powerbev/utils/instance.py#L19-L41) (only used in FIERY, not in PowerBEV)  

Similarly, you also need to change the configuration in other parts to the corresponding KITTI settings.
